### ISSUE TITLE
Unit Test Implementation

### ISSUE THREAD

**Issue by cbatista8a** [CubaDevOps/flexi#2] opened 2024-06-08 19:15 UTC
- Cover 100% of Domain layer
- Cover 100% of Application layer

**Comment by Qupiter** [comment] 2024-06-11 17:15
Hey, Carlos,

Could you assign this to me? I would like to work with you if possible.

I see this is a new project, maybe we can exchange information (skype/teams)

**Comment by cbatista8a** [comment] 2024-06-11 18:26
Hi, yes sure 👍 Enviado desde mi iPhone7PlusEl 11 jun 2024, a las 19:15, Qupiter ***@***.***> escribió:﻿
Hey, Carlos,
Could you assign this to me? I would like to work with you if possible.

**Comment by Qupiter** [comment] 2024-06-12 10:41
Hey again Carlos,

I am currently testing the Container.php in domain layer and experiencing some difficulties with session_start().
I load the services from the /Config directory. I am providing you with some screenshots. 

Do you have a clue where the problem is?

![image](https://github.com/CubaDevOps/flexi/assets/160345217/531e51e1-4eaf-4924-87bd-6ee5aecd76fb)
![image](https://github.com/CubaDevOps/flexi/assets/160345217/a2f10847-132f-4b51-af94-8d73a0514236)
![image](https://github.com/CubaDevOps/flexi/assets/160345217/e879d2d9-cad8-4c31-af51-368cac226e32)

**Comment by Qupiter** [comment] 2024-06-12 11:18
Testing further into the container services I might have found a bug loading the commands.json.
Path starts with '/' for some reason.

![image](https://github.com/CubaDevOps/flexi/assets/160345217/74a58b54-728d-4179-ad4f-39dac3d3dd1e)

I think it is caused by the path normalization in FileHandlerTrait.php

![image](https://github.com/CubaDevOps/flexi/assets/160345217/bf72a5bf-85c9-41fb-a137-953bb4033847)

**Comment by cbatista8a** [comment] 2024-06-12 20:19
> Hey again Carlos,
> 
> I am currently testing the Container.php in domain layer and experiencing some difficulties with session_start(). I load the services from the /Config directory. I am providing you with some screenshots.
> 
> Do you have a clue where the problem is?
> 


Usually the error "Session cannot be started after headers have already been sent" is due to some output being sent before the session started, some "echo" perhaps or some test output. Try just running the container test separately to rule out any previous output.

**Comment by cbatista8a** [comment] 2024-06-12 20:32
> Testing further into the container services I might have found a bug loading the commands.json. Path starts with '/' for some reason.

I have moved this comment to a separate [issue 5](https://github.com/CubaDevOps/flexi/issues/5). You can open new independent issues as you find them. Thanks for the support.

**Comment by Qupiter** [comment] 2024-06-13 06:57
Hey Carlos, 

Seems like I don't have permission to open branches or change issue status from the github ui and if I push my changes in a custom branch I fear that it wouldn't be able to associate the branch with the issue. Could you have a look at that, or just open for me branches for both the unit tests and the bug from yesterday?

**Comment by Qupiter** [comment] 2024-06-13 08:48
> > Hey again Carlos,
> > I am currently testing the Container.php in domain layer and experiencing some difficulties with session_start(). I load the services from the /Config directory. I am providing you with some screenshots.
> > Do you have a clue where the problem is?
> 
> Usually the error "Session cannot be started after headers have already been sent" is due to some output being sent before the session started, some "echo" perhaps or some test output. Try just running the container test separately to rule out any previous output.

Yes, I tried to resolve it but seems like something in the autoload.php causes it.
If I add 'ob_start();' before the ComposerAutoloader it fixes the problem but not after.
I am not sure how to approach this problem.
![image](https://github.com/CubaDevOps/flexi/assets/160345217/d7262a8f-d16f-400c-ad7a-badbecf19ec0)

**Comment by cbatista8a** [comment] 2024-06-13 15:19
> Hey Carlos,
> 
> Seems like I don't have permission to open branches or change issue status from the github ui and if I push my changes in a custom branch I fear that it wouldn't be able to associate the branch with the issue. Could you have a look at that, or just open for me branches for both the unit tests and the bug from yesterday?

i open the `unit-test-implementation` branch for this issue

**Comment by Qupiter** [comment] 2024-06-13 16:56
Committed some Unit tests, you can have a look at them as well if there is anything you don't like.

**Comment by Qupiter** [comment] 2024-06-13 17:00
I noticed that CliDTOInterface.php does not exist any more, or is it renamed to something else.  CommandListDTO.php class is causing some tests to fail. 

Note: I am used to only working with jira but I will do my best. I apologise if I do anything by mistake.

**Comment by cbatista8a** [comment] 2024-06-13 17:40
> I noticed that CliDTOInterface.php does not exist any more, or is it renamed to something else. CommandListDTO.php class is causing some tests to fail.
> 
> Note: I am used to only working with jira but I will do my best. I apologise if I do anything by mistake.

Yes, I had forgotten to send the file and I just fixed it now. 😅

**Comment by Qupiter** [comment] 2024-06-14 07:35
Still, there are problems with the NativeSessionStorage.php. I will commit a new version of the Unit test for you to be able to run it. 'session_unset();' does not work properly because it unsets the global $_SESSION but storage is not empty afterwards, and if I want to create an instance of NativeSessionStorage I must explicitly have a $_SESSION variable beforehand. Otherwise, the property $storage of type array does not accept null. If this is expected behaviour, it should probably be wrapped in some way.
![image](https://github.com/CubaDevOps/flexi/assets/160345217/de151500-d777-4909-97bd-dd86e289a824)

**Comment by Qupiter** [comment] 2024-06-14 07:58
headersSent() check for the session is probably incorrect because even when I go into logger->error() case after that it does not throw the implemented RuntimeException, instead it proceeds to create a new instance.
![image](https://github.com/CubaDevOps/flexi/assets/160345217/cf78804b-0e4f-4ac1-b3c5-1e7176387d1e)
I tried to find the logs into the var folder but I could not find any.
From here I see that the problem is PHPUnit itself, since it prints information about the library when run. 
Solution might be just checking if the current environment is 'development'. I provide you with a screenshot.
![image](https://github.com/CubaDevOps/flexi/assets/160345217/2e94c9e0-d037-4b19-a13c-f4aa2cbfbdef)

**Comment by cbatista8a** [comment] 2024-06-14 08:52
@Qupiter can you join to [slack channel](https://join.slack.com/t/cubadevops/shared_invite/zt-2krpi3hkm-7ipas5seclBWGik6SCtjMQ) to discuss about?

**Closed as completed** 2024-07-02 21:04 UTC
Labels: enhancement, good first issue, help wanted
